### PR TITLE
Add note that it is built in with Crystal 0.9.0

### PR DESCRIPTION
**Pull request by adlerhsieh**
Update README.

### CODE REVIEW

**Comment by jhass** [comment]
built-in is a bit misleading, how about "comes with the official Crystal packages since Crystal 0.9.0"?

**Comment by adlerhsieh** [comment]
Yeap that makes more sense. Thanks. Updated.

**Comment by ysbaddaden** [comment]
I will wait for Crystal v0.10.0 to add that note. The bundled shards [has a problem](https://github.com/ysbaddaden/shards/pull/63#issuecomment-148857947).

**Comment by adlerhsieh** [comment]
Got it. I think to include both `shards` (Mac) and `crystal shards` (Linux) commands is better. I'll update the commit when 0.10.0 is out.

**Pull request closed without merging**
